name: 'Setup Python Environment'
description: 'Setup Python with dependencies for jsonschema-diff'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
  install-dev:
    description: 'Install development dependencies'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
